name: PR Reviewer Changed

on:
  pull_request:
    types:
      - review_requested

jobs:
  add_to_project:
    runs-on: windows-latest

    steps:
      - name: Check Reviewer
        run: echo ${{ github.event.pull_request.requested_reviewers[-1].login }}
