name: PR Reviewer Changed

on:
  pull_request:
    types:
      - review_requested
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Pull Request to Project
        # https://github.com/marketplace/actions/assign-to-one-project
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: ${{ 1 == 1 }}
        with:
          project: 'https://github.com/users/wannacfuture/projects/3'
          column_name: 'In Progress'
