name: PR Reviewer Changed

on:
  pull_request:
    types:
      - review_requested
env:
  GITHUB_TOKEN: ${{ secrets.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 }}
  MY_GITHUB_TOKEN: ${{ secrets.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 }}

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Pull Request to Project
        # https://github.com/marketplace/actions/assign-to-one-project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: ${{ 1 == 1 }}
        with:
          project: 'https://github.com/users/wannacfuture/projects/3'
          column_name: 'In Progress'
