name: Add pull requests to project

on:
  pull_request:
    types:
      - review_requested

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Check if requested reviewer is 'A'
        id: check_reviewer
        run: |
          if [[ ${{ github.event.pull_request.requested_reviewers[*].login }} == 'wannacfuture' ]]; then
            echo "::set-output name=valid::true"
          else
            echo "::set-output name=valid::false"
          fi

      - name: Add to project if reviewer is 'A'
        if: steps.check_reviewer.outputs.valid == 'true'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/wannacfuture/projects/3
          github-token: ${{ secrets.PAT_TOKEN }}
